code 1 
class Main {
    public static void main(String[] args) {
        try {
            // code that generates exception
            int divideByZero = 5 / 0;
            System.out.println("rest of code in try block");
        } catch (ArithmeticException e) {
            System.out.println("ArithmeticException => " + e.getMessage());
        }
    }
}

 code 2
 public class Exc {
    public static void main(String[] args) {
        try {
            // code that may raise exception
            int data = 100 / 0;
        } catch (ArithmeticException e) {
            System.out.println(e);
        }

        // rest code of the program
        System.out.println("A number cannot be divided by zero");
    }
}
